
# Lord of the Ring game engine Makefile configuration

# set this to 1 if you want debug version (including cheats)
DEBUG=0

# set this to 1 if you want extended version
# currently only for testing (use together with debug)
EXTENDED=0

# set this to 1 to compile game demo
DEMO=0
