char *object_names2[] = { /*  0 */ "silver pennies",
    /*  1 */ "Illuminate",
    /*  2 */ "Unlock",
    /*  3 */ "Firefinger",
    /*  4 */ "Firestorm",
    /*  5 */ "Knowledge",
    /*  6 */ "Animalspeak",
    /*  7 */ "Vinecrush",
    /*  8 */ "Persuasion",
    /*  9 */ "Black Breath",
    /*  a */ "Healing Hand",
    /*  b */ "Winterchill",
    /*  c */ "Sleeper",
    /*  d */ "Countermagic",
    /*  e */ "",
    /*  f */ "",
    /* 10 */ "!Help Help",
    /* 11 */ "!Elbereth",
    /* 12 */ "!Fingon",
    /* 13 */ "!Edro",
    /* 14 */ "!Gwaihir",
    /* 15 */ "!Manwe",
    /* 16 */ "!Fimbretthil",
    /* 17 */ "!Felagund",
    /* 18 */ "",
    /* 19 */ "",
    /* 1a */ "",
    /* 1b */ "",
    /* 1c */ "",
    /* 1d */ "",
    /* 1e */ "",
    /* 1f */ "",
    /* 20 */ "",
    /* 21 */ "",
    /* 22 */ "",
    /* 23 */ "",
    /* 24 */ "",
    /* 25 */ "",
    /* 26 */ "",
    /* 27 */ "",
    /* 28 */ "",
    /* 29 */ "",
    /* 2a */ "",
    /* 2b */ "",
    /* 2c */ "",
    /* 2d */ "",
    /* 2e */ "",
    /* 2f */ "",
    /* 30 */ "",
    /* 31 */ "",
    /* 32 */ "",
    /* 33 */ "",
    /* 34 */ "",
    /* 35 */ "",
    /* 36 */ "",
    /* 37 */ "",
    /* 38 */ "",
    /* 39 */ "",
    /* 3a */ "",
    /* 3b */ "",
    /* 3c */ "",
    /* 3d */ "",
    /* 3e */ "",
    /* 3f */ "",
    /* 40 */ "brawl",
    /* 41 */ "swords",
    /* 42 */ "axes",
    /* 43 */ "maces",
    /* 44 */ "staff",
    /* 45 */ "bows",
    /* 46 */ "dodge",
    /* 47 */ "hide",
    /* 48 */ "climb",
    /* 49 */ "swim",
    /* 4a */ "jump",
    /* 4b */ "perception",
    /* 4c */ "ride",
    /* 4d */ "picklock",
    /* 4e */ "sneak",
    /* 4f */ "read",
    /* 50 */ "charisma",
    /* 51 */ "detect traps",
    /* 52 */ "devices",
    /* 53 */ "bravado",
    /* 54 */ "ironmind",
    /* 55 */ "boat",
    /* 56 */ "Numenorean lore",
    /* 57 */ "Dwarf lore",
    /* 58 */ "Orc lore",
    /* 59 */ "Hobbit lore",
    /* 5a */ "Elven lore",
    /* 5b */ "herb lore",
    /* 5c */ "Ranger lore",
    /* 5d */ "Wizard lore",
    /* 5e */ "Dark lore",
    /* 5f */ "",
    /* 60 */ "Sting",
    /* 61 */ "Barrow Dagger",
    /* 62 */ "Anduril",
    /* 63 */ "Glamdring",
    /* 64 */ "Spider Sword",
    /* 65 */ "Magic Bow",
    /* 66 */ "Troll slayer",
    /* 67 */ "Durin's axe",
    /* 68 */ "spear",
    /* 69 */ "Magic Sword",
    /* 6a */ "Herugrim",
    /* 6b */ "",
    /* 6c */ "",
    /* 6d */ "",
    /* 6e */ "",
    /* 6f */ "",
    /* 70 */ "dagger",
    /* 71 */ "sword",
    /* 72 */ "staff",
    /* 73 */ "axe",
    /* 74 */ "mace",
    /* 75 */ "club",
    /* 76 */ "flail",
    /* 77 */ "bow",
    /* 78 */ "torch",
    /* 79 */ "knife",
    /* 7a */ "",
    /* 7b */ "",
    /* 7c */ "",
    /* 7d */ "",
    /* 7e */ "",
    /* 7f */ "",
    /* 80 */ "cloth armor",
    /* 81 */ "leather armor",
    /* 82 */ "chain mail",
    /* 83 */ "magic mail",
    /* 84 */ "mithril mail",
    /* 85 */ "skin",
    /* 86 */ "hide",
    /* 87 */ "scales",
    /* 88 */ "shield",
    /* 89 */ "magic shield",
    /* 8a */ "",
    /* 8b */ "",
    /* 8c */ "",
    /* 8d */ "",
    /* 8e */ "",
    /* 8f */ "",
    /* 90 */ "",
    /* 91 */ "",
    /* 92 */ "",
    /* 93 */ "",
    /* 94 */ "The Ring",
    /* 95 */ "",
    /* 96 */ "",
    /* 97 */ "",
    /* 98 */ "",
    /* 99 */ "",
    /* 9a */ "",
    /* 9b */ "",
    /* 9c */ "",
    /* 9d */ "",
    /* 9e */ "Morgul water",
    /* 9f */ "statue head",
    /* a0 */ "fish",
    /* a1 */ "rock",
    /* a2 */ "boulder",
    /* a3 */ "gianthands",
    /* a4 */ "rations",
    /* a5 */ "herb",
    /* a6 */ "prybar",
    /* a7 */ "vine",
    /* a8 */ "spirit key",
    /* a9 */ "star ruby",
    /* aa */ "athelas",
    /* ab */ "elf cloak",
    /* ac */ "ale",
    /* ad */ "phial",
    /* ae */ "supply key",
    /* af */ "pipe",
    /* b0 */ "pipeweed",
    /* b1 */ "shovel",
    /* b2 */ "rope",
    /* b3 */ "White Hand",
    /* b4 */ "pick",
    /* b5 */ "hot food",
    /* b6 */ "elf rope",
    /* b7 */ "dwarfwort",
    /* b8 */ "red beans",
    /* b9 */ "bottle",
    /* ba */ "amulet",
    /* bb */ "entwater",
    /* bc */ "red acorn",
    /* bd */ "oracle",
    /* be */ "elfdraught",
    /* bf */ "leaf belt",
    /* c0 */ "necklace",
    /* c1 */ "bracelet",
    /* c2 */ "Galadrial's box",
    /* c3 */ "Golden Wheel",
    /* c4 */ "eagle egg",
    /* c5 */ "flint",
    /* c6 */ "scroll",
    /* c7 */ "palantir",
    /* c8 */ "ent seed",
    /* c9 */ "fountain water",
    /* ca */ "black cloak",
    /* cb */ "miruvor",
    /* cc */ "reforge-ring",
    /* cd */ "wine bottle",
    /* ce */ "Saruman's key",
    /* cf */ "spiderbane",
    /* d0 */ "silver horn",
    /* d1 */ "Helm's horn",
    /* d2 */ "Grima's box",
    /* d3 */ "scabbard",
    /* d4 */ "elven cape",
    /* d5 */ "elfstone",
    /* d6 */ "magic glass",
    /* d7 */ "iron key I",
    /* d8 */ "iron key II",
    /* d9 */ "iron key III",
    /* da */ "warm clothes",
    /* db */ "bridle",
    /* dc */ "sceptre",
    /* dd */ "Cup of Rohan",
    /* de */ "healing draught",
    /* df */ "Smith's ring",
    /* e0 */ "pony",
    /* e1 */ "mushrooms",
    /* e2 */ "tree bark",
    /* e3 */ "ent wife's key",
    /* e4 */ "Tinalin's cape",
    /* e5 */ "source water",
    /* e6 */ "gauntlet",
    /* e7 */ "Ice staff",
    /* e8 */ "water",
    /* e9 */ "flower",
    /* ea */ "moonstone",
    /* eb */ "elf brooch",
    /* ec */ "red fungus",
    /* ed */ "Durin's pick",
    /* ee */ "jewelry",
    /* ef */ "stone block",
    /* f0 */ "mithril",
    /* f1 */ "gem",
    /* f2 */ "bag of gold",
    /* f3 */ "wizard staff",
    /* f4 */ "Eagle Gem",
    /* f5 */ "lembas",
    /* f6 */ "ent draught",
    /* f7 */ "grond",
    /* f8 */ "black acorn",
    /* f9 */ "worms",
    /* fa */ "hooks",
    ""
};
