
#define SOUNDS_NUM 32

char *sound_names[] = { "magics.adl",
    "magicf.adl",
    "hit1.adl",
    "hit2.adl",
    "hit3.adl",
    "hit4.adl",
    "miss1.adl",
    "miss2.adl",
    "miss3.adl",
    "howl.adl",
    "moan.adl",
    "crow.adl",
    "gallop.adl",
    "beep.adl",
    "buzz.adl",
    "qmiss.adl",
    "dmiss.adl",
    "bmiss.adl",
    "qhit.adl",
    "hhit.adl",
    "ihit.adl",
    "grunt.adl",
    "yell.adl",
    "shriek.adl",
    "screech.adl",
    "hiss.adl",
    "growl.adl",
    "snarl.adl",
    "bswish.adl",
    "ahiss.adl",
    "whip.adl",
    "tgrunt.adl"
};
