name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: |
        sudo apt-get install -y libsdl2-dev libxml2-dev
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck
